# This is a basic workflow to help you get started with Actions

name: RPM Build

# Controls when the action will run. Triggers the workflow on push 
on: --push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: Antikythera/build-rpm@v1
      id: build_rpm
      with:
        spec_file: cello.spec
        sources: cello-1.0.2.tar.gz

    - name: Upload RPM
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: my_app.rpm
        asset_path: ${{ steps.build_rpm.outputs.rpm_package_path }}
        asset_name: ${{ steps.build_rpm.outputs.rpm_package_name }}
        asset_content_type: application/octet-stream
