# This is a basic workflow to help you get started with Actions

name: RPM Build3

# Controls when the action will run. Triggers the workflow on push 

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rpmbuild
        uses: robertdebock/rpmbuild-action@1.1.1